# Reporting unite test coverage to CodeCov is disabled
# I give up, I just can't set i up, 3 days totally  and irreversibely wasted

language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24

notifications:
  slack: codarama:YVl3XmRANEPWD74rdOErjXGG

before_install:
# (disable coverage )
#  - sudo pip install codecov

# Call gradle build, current CI target builds and executes tests
script: ./gradlew testDebugUnitTest --info

# (disable coverage )
# after_success:
#  - codecov