# Reporting unite test coverage to CodeCov is disabled
# I give up, I just can't set i up, 3 days totally  and irreversibely wasted

language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.1
    - android-23

notifications:
  slack: codarama:YVl3XmRANEPWD74rdOErjXGG

before_install:
# (disable coverage )
#  - sudo pip install codecov

  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

# Call gradle build, current CI target builds and executes tests
script: ./gradlew testDebugUnitTest --info

# (disable coverage )
# after_success:
#  - codecov